// <auto-generated />
namespace MySQL_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Length_Constraints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Length_Constraints));
        
        string IMigrationMetadata.Id
        {
            get { return "201403241629245_Length_Constraints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
